### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jlacko**
I suggest an update in the readme - from http >> https - the original image was broken

no real functionality, just a presentation issue...

### CODE REVIEW

**Comment by mpadge** [comment]
Thanks! Could you actually do this via:
``` r
urlchecker::url_update()
```
That will then update both files, and ensure everything is fixed.

**Comment by jlacko** [comment]
thank you for teaching me a new package! done with urlchecker

**Comment by jlacko** [comment]
on second thought: the urlchecker seems to be perhaps too aggressive - it actually broke the codecov badge (corrected now)

**Comment by mpadge** [comment]
Thank you very much @jlacko, you'll added to the allcontributions section of readme in next commit, which'll be linked below ...

**Comment by mpadge** [comment]
Hey, it's all "allcontributors". Plus I just published [this blog post](https://ropensci.org/blog/2024/11/26/allcontributors/), and this is just me doing what I say there :smile:

**Pull request merged**
